export const divProperties = [
	{
		utility: "spacing",
		properties: [
			["margin", "margin"],
			["margin-block", "marginBlock"],
			["margin-bottom", "marginBottom"],
			["margin-inline", "marginInline"],
			["margin-left", "marginLeft"],
			["margin-right", "marginRight"],
			["margin-top", "marginTop"],
			["padding", "padding"],
			["padding-block", "paddingBlock"],
			["padding-bottom", "paddingBottom"],
			["padding-inline", "paddingInline"],
			["padding-left", "paddingLeft"],
			["padding-right", "paddingRight"],
			["padding-top", "paddingTop"],
		],
	},
	{
		utility: "borders",
		properties: [
			["border", "border"],
			["border-radius", "borderRadius"],
			["border-bottom", "borderBottom"],
			["border-bottom-left-radius", "borderBottomLeftRadius"],
			["border-bottom-right-radius", "borderBottomRightRadius"],
			["border-bottom-style", "borderBottomStyle"],
			["border-image", "borderImage"],
			["border-image-outset", "borderImageOutset"],
			["border-image-repeat", "borderImageRepeat"],
			["border-image-slice", "borderImageSlice"],
			["border-image-source", "borderImageSource"],
			["border-image-width", "borderImageWidth"],
			["border-left", "borderLeft"],
		],
	},
	{
		utility: "backgrounds",
		properties: [
			["background", "background"],
			["background-attachment", "backgroundAttachment"],
			["background-clip", "backgroundClip"],
			["background-color", "backgroundColor"],
			["background-image", "backgroundImage"],
			["background-origin", "backgroundOrigin"],
			["background-position", "backgroundPosition"],
			["background-repeat", "backgroundRepeat"],
			["background-size", "backgroundSize"],
		],
	},
	{
		utility: "text",
		properties: [
			["color", "color"],
			["font", "font"],
			["font-family", "fontFamily"],
			["font-size", "fontSize"],
			["font-style", "fontStyle"],
			["font-variant", "fontVariant"],
			["font-weight", "fontWeight"],
			["letter-spacing", "letterSpacing"],
			["line-height", "lineHeight"],
			["text-align", "textAlign"],
			["text-decoration", "textDecoration"],
			["text-indent", "textIndent"],
			["text-overflow", "textOverflow"],
			["text-shadow", "textShadow"],
			["text-transform", "textTransform"],
			["white-space", "whiteSpace"],
			["word-spacing", "wordSpacing"],
			["word-wrap", "wordWrap"],
		],
	},
	{
		utility: "layout",
		properties: [
			["display", "display"],
			["height", "height"],
			["max-height", "maxHeight"],
			["max-width", "maxWidth"],
			["min-height", "minHeight"],
			["min-width", "minWidth"],
			["overflow", "overflow"],
			["overflow-x", "overflowX"],
			["overflow-y", "overflowY"],
			["visibility", "visibility"],
			["width", "width"],
		],
	},
	{
		utility: "positioning",
		properties: [
			["bottom", "bottom"],
			["top", "top"],
			["left", "left"],
			["right", "right"],
			["position", "position"],
			["z-index", "zIndex"],
		],
	},
	{
		utility: "flexbox",
		properties: [
			["align-content", "alignContent"],
			["align-items", "alignItems"],
			["align-self", "alignSelf"],
			["flex", "flex"],
			["flex-basis", "flexBasis"],
			["flex-direction", "flexDirection"],
			["flex-flow", "flexFlow"],
			["flex-grow", "flexGrow"],
			["flex-shrink", "flexShrink"],
			["flex-wrap", "flexWrap"],
			["justify-content", "justifyContent"],
			["justify-items", "justifyItems"],
			["justify-self", "justifySelf"],
			["order", "order"],
		],
	},
	{
		utility: "grid",
		properties: [
			["grid", "grid"],
			["grid-area", "gridArea"],
			["grid-auto-columns", "gridAutoColumns"],
			["grid-auto-flow", "gridAutoFlow"],
			["grid-auto-rows", "gridAutoRows"],
			["grid-column", "gridColumn"],
			["grid-column-end", "gridColumnEnd"],
			["grid-column-gap", "gridColumnGap"],
			["grid-column-start", "gridColumnStart"],
			["grid-gap", "gridGap"],
			["grid-row", "gridRow"],
			["grid-row-end", "gridRowEnd"],
			["grid-row-gap", "gridRowGap"],
			["grid-row-start", "gridRowStart"],
			["grid-template", "gridTemplate"],
			["grid-template-areas", "gridTemplateAreas"],
			["grid-template-columns", "gridTemplateColumns"],
			["grid-template-rows", "gridTemplateRows"],
		],
	},
	{
		utility: "transform",
		properties: [
			["transform", "cssTransform"],
			["transform-origin", "transformOrigin"],
			["transform-style", "transformStyle"],
			["backface-visibility", "backfaceVisibility"],
			["perspective", "perspective"],
			["perspective-origin", "perspectiveOrigin"],
		],
	},
	{
		utility: "transitions",
		properties: [
			["transition", "cssTransition"],
			["transition-delay", "transitionDelay"],
			["transition-duration", "transitionDuration"],
			["transition-property", "transitionProperty"],
			["transition-timing-function", "transitionTimingFunction"],
		],
	},
	{
		utility: "animation",
		properties: [
			["animation", "animation"],
			["animation-delay", "animationDelay"],
			["animation-direction", "animationDirection"],
			["animation-duration", "animationDuration"],
			["animation-fill-mode", "animationFillMode"],
			["animation-iteration-count", "animationIterationCount"],
		],
	},
	{
		utility: "scroll",
		properties: [
			["scroll-behavior", "scrollBehavior"],
			["scroll-snap-type", "scrollSnapType"],
			["scroll-snap-destination", "scrollSnapDestination"],
			["scroll-snap-coordinate", "scrollSnapCoordinate"],
			["scroll-snap-points-x", "scrollSnapPointsX"],
			["scroll-snap-points-y", "scrollSnapPointsY"],
			["scroll-snap-destination", "scrollSnapDestination"],
			["scroll-snap-type-x", "scrollSnapTypeX"],
			["scroll-snap-type-y", "scrollSnapTypeY"],
			["scroll-padding", "scrollPadding"],
			["scroll-padding-top", "scrollPaddingTop"],
			["scroll-padding-right", "scrollPaddingRight"],
			["scroll-padding-bottom", "scrollPaddingBottom"],
			["scroll-padding-left", "scrollPaddingLeft"],
		],
	},
	{
		utility: "filters",
		properties: [
			["filter", "filter"],
			["backdrop-filter", "backdropFilter"],
		],
	},
	{
		utility: "effects",
		properties: [
			["box-shadow", "boxShadow"],
			["opacity", "opacity"],
			["mix-blend-mode", "mixBlendMode"],
			["isolation", "isolation"],
		],
	},
	{
		utility: "interactivity",
		properties: [
			["cursor", "cursor"],
			["pointer-events", "pointerEvents"],
			["user-select", "userSelect"],
			["resize", "resize"],
			["appearance", "appearance"],
			["outline", "outline"],
			["outline-offset", "outlineOffset"],
			["will-change", "willChange"],
		],
	},
];
